exec --no-startup-id xss-lock --transfer-sleep-lock -- bash ~/.local/bin/lock.sh
exec_always --no-startup-id copyq
exec_always --no-startup-id picom --daemon --config ~/.config/picom/picom.conf
exec_always --no-startup-id bash ~/.local/bin/dunst.sh
exec_always --no-startup-id bash ~/.local/bin/polybar.sh
exec_always --no-startup-id bash ~/.fehbg
