[greeter]
background = #301934
clock-format = %d/%m/%y %A %H:%M
font-name = JetBrains Mono Regular 12
icon-theme-name = Papirus
indicators = ~clock;~spacer;~session;~separator;~layout;~separator;~power
screensaver-timeout = 0
user-background = false
xft-antialias = true
xft-dpi = 96
xft-rgba = rgb
