[greeter]
background = /usr/share/backgrounds/2b.jpg
font-name = MesloLGS NF 12
icon-theme-name = Papirus
xft-antialias = true
xft-dpi = 96
xft-rgba = rgb
indicators = ~clock;~spacer;~session;~separator;~layout;~separator;~power
clock-format = %d/%m/%y %A %H:%M
user-background = false
screensaver-timeout = 0
