filetype plugin indent on
set clipboard=unnamedplus
set encoding=UTF-8
set expandtab
set history=10000
set incsearch
set laststatus=2
set list
set listchars=trail:^
set nobackup
set nocompatible
set noshowmatch
set scrolloff=8
set shiftwidth=4
set showmode
set smartindent
set softtabstop=4
set tabstop=4
set whichwrap+=<,>,[,]
syntax on
