[colors]
background = #301934
foreground = #faf9f6


[bar/primary]
monitor = eDP-1
; monitor = Virtual1

bottom = false

override-redirect = false

enable-ipc = true

modules-left = i3
modules-center = date
modules-right = bluetooth backlight wired wireless pulseaudio battery

fixed-center = true

width = 100%
height = 50

background = ${colors.background}
foreground = ${colors.foreground}

radius = 0

padding-left = 0
padding-right = 2

module-margin = 2

font-0 = RobotoMono Nerd Font:style=Regular;size=12;0

dpi-x = 0
dpi-y = 0


[bar/external]
monitor = HDMI-1

inherit = bar/primary


[module/i3]
type = internal/i3

pin-workspaces = true

index-sort = true

enable-scroll = false

format = <label-state> <label-mode>

label-mode = %mode%
label-mode-padding = 2
label-mode-background = #d2042d

label-focused =  %index%
label-focused-padding = 3
label-focused-background = #3f3f3f

label-unfocused = %index%
label-unfocused-padding = 3

label-visible = %index%
label-visible-padding = 3

label-urgent = %index%
label-urgent-padding = 3


[module/date]
type = internal/date

interval = 1

time = %H:%M:%S
time-alt = %d/%m/%y %A

format = <label>

label = %time%


[module/bluetooth]
type = custom/ipc

format = <label>

label = 

hook-0 = blueberry

click-left = #bluetooth.hook.0


[module/backlight]
type = internal/backlight

poll-interval = 0

card = intel_backlight

use-actual-brightness = true

enable-scroll = true

scroll-interval = 10

format = <ramp> <label>

label = %percentage:3%%

ramp-0 = 󰃜
ramp-1 = 󰃛
ramp-2 = 󰃚


[module/wired]
type = internal/network

interval = 3

interface = eth0

interface-type = wired

unknown-as-up = false

format-connected = 󰈁
format-disconnected = 󰈂


[module/wireless]
type = internal/network

interval = 3

interface = wlan0

interface-type = wireless

unknown-as-up = false

format-connected = <ramp-signal>
format-disconnected = 󰤭

ramp-signal-0 = 󰤯
ramp-signal-1 = 󰤟
ramp-signal-2 = 󰤢
ramp-signal-3 = 󰤥
ramp-signal-4 = 󰤨


[module/pulseaudio]
type = internal/pulseaudio

interval = 5

use-ui-max = false

format-volume = <ramp-volume> <label-volume>
format-muted = 󰕿 <label-muted>

label-volume = %percentage:3%%
label-muted = %percentage:3%%

ramp-volume-0 = 󰖀
ramp-volume-1 = 󰕾

click-left = pavucontrol
click-right = pavucontrol


[module/battery]
type = internal/battery

poll-interval = 5

full-at = 99
low-at = 5

battery = BAT0

format-charging = <animation-charging> <label-charging>
format-discharging = <ramp-capacity> <label-discharging>
format-full = 󰁹 <label-full>
format-low = <ramp-capacity> <label-low>

label-charging = %percentage:3%%
label-discharging = %percentage:3%%
label-full = %percentage:3%%
label-low = %percentage:3%%

ramp-capacity-0 = 󰂎
ramp-capacity-1 = 󰂎
ramp-capacity-2 = 󱊡
ramp-capacity-3 = 󱊡
ramp-capacity-4 = 󱊢
ramp-capacity-5 = 󱊢
ramp-capacity-6 = 󱊣
ramp-capacity-7 = 󱊣

animation-charging-framerate = 1000

animation-charging-0 = 󰂎
animation-charging-1 = 󰂎
animation-charging-2 = 󱊡
animation-charging-3 = 󱊡
animation-charging-4 = 󱊢
animation-charging-5 = 󱊢
animation-charging-6 = 󱊣
animation-charging-7 = 󱊣
